### ISSUE TITLE
Won't accept any other videos

### ISSUE THREAD

**Issue by jjfster** [Fedenieto90/ArKitImageRecognizer#1]
I'm trying to load my own mp4 or mov, but all I get is a white box instead of the video to play on the recognized image.  The videos included with the demo play fine.  Can you assist please?

**Comment by Fedenieto90** [comment]
Did it finally work @jjfster ?

**Comment by jjfster** [comment]
Yes, Thank you. 

Sorry I bothered you.  I didn't notice I did not add it to the target.

Fun stuff btw.

**Comment by Fedenieto90** [comment]
Great to hear that! Thanks!
